### ISSUE TITLE
Crashes when using EMC condenserMK2

### ISSUE THREAD

**Issue by NyanjiroJPN** [sousuke0422/ProjectE#1]
EMC CondenserMK2 crashes when an item is registered in the source item slot.
MK1 is not a problem.

**Comment by NyanjiroJPN** [comment]
Some PE Addon's condenser and collecto also seem to cause crashes
PEAA, PEEX, ProjectEAddon Extra Alchemy, etc.

**Comment by sousuke0422** [comment]
This is the effect of api becoming a Long type.
PEAA should use FMPEAA.

**Comment by sousuke0422** [comment]
PEEX is an ARR and there is no other way to fix it but with mixins or something.
ProjectEAddon Extra Alchemy is not known to me, so if you could tell me where it is distributed, I might be able to figure out how to fix it.

**Comment by sousuke0422** [comment]
The NEI modifications may be backported to the version 1 family.
In this case the original add-on should be available.

**Comment by sousuke0422** [comment]
https://lab.teamblackcrystal.com/fmmods/fmprojecte/-/jobs/3138/artifacts/file/build/libs/FMProjectE-1.1.0-git.8+b80b4c557b.jar
Try this build!

Probably should not cause any problems, but the EMC will be relaxed to 2.1 billion.

**Comment by NyanjiroJPN** [comment]
ProjectEAddon Extra Alchemy is a mod created by an individual and is no longer publicly available...
If you can't use FMPE, you can give up the other addon
But I will try the modified version!

**Comment by sousuke0422** [comment]
Hello @NyanjiroJPN , did it work?

**Comment by NyanjiroJPN** [comment]
It worked!
No longer crashes when using collectors or capacitors!
Stack EMC is 2.1 billion, but that's more than the original PE, and that's very satisfying.
But I'm using FMPE 2.2.2 right now.
It's not a mod I use very often, so I thought build_2.2.2 would be fine.
